#!/usr/bin/env bash
# Research env egress allowlist.
#
# Egress is filtered by HOSTNAME, not by IP. A small squid forward proxy holds
# the allowlist and is the default route out (HTTPS_PROXY points every client at
# it); squid matches the host in each CONNECT on a dstdomain allowlist, so a
# leading-dot wildcard like `.amazonaws.com` is honored directly and rotating
# cloud endpoint IPs are a non-issue. (An IP-pinned firewall cannot allow AWS:
# its regional endpoints resolve to large, fast-rotating pools, so the IP the
# SDK connects to is almost never the one pinned at startup.)
#
# The base infra domains (the agent's own API, GitHub, package registries) are
# ALSO pinned by IP into an ipset, as a direct-egress fallback: if the agent
# runtime ignores HTTPS_PROXY it can still reach those stable endpoints. Nothing
# else may leave the container directly — only squid (running as the `proxy`
# user) may open arbitrary outbound web connections, and squid enforces the
# allowlist on every one.
#
# Adapted from the Anthropic / Trail of Bits reference devcontainer pattern.
#
# The compiled allowlist (ALL_ALLOWED_DOMAINS) arrives as the FIRST ARGUMENT
# (space-separated), because post-create.sh invokes this via `sudo`, and sudo's
# `env_reset` would otherwise strip the env var — silently dropping every
# platform domain (this is why AWS was unreachable even before IP rotation bit).
# Arguments survive sudo; the env var is kept only as a fallback for a direct,
# non-sudo invocation (e.g. tests).
set -euo pipefail

EXTRA="${1:-${ALL_ALLOWED_DOMAINS:-}}"

# Stable infra the harness itself needs. These get both paths (proxy + pinned-IP
# fallback); platform domains from ALL_ALLOWED_DOMAINS get the proxy only.
BASE_DOMAINS=(
  "api.anthropic.com"
  "statsig.anthropic.com"
  "claude.ai"
  "api.github.com"
  "github.com"
  "objects.githubusercontent.com"
  "raw.githubusercontent.com"
  "codeload.github.com"
  "registry.npmjs.org"
  "pypi.org"
  "files.pythonhosted.org"
  "deb.debian.org"
  "security.debian.org"
)

# Full allowlist = base infra + every platform/extra domain. squid filters on it.
ALLOWED_DOMAINS=("${BASE_DOMAINS[@]}")
for d in ${EXTRA}; do
  ALLOWED_DOMAINS+=("${d}")
done

# ── 1. squid: the domain allowlist proxy ────────────────────────────────────
# Build the dstdomain list, dropping any exact host already covered by a
# leading-dot wildcard (squid warns when a domain and its subdomain share an
# ACL). A leading dot means "this apex and all subdomains".
declare -a WILDCARDS=() DSTDOMAINS=()
for d in "${ALLOWED_DOMAINS[@]}"; do
  [[ "${d}" == .* ]] && WILDCARDS+=("${d}")
done
for d in "${ALLOWED_DOMAINS[@]}"; do
  covered=0
  if [[ "${d}" != .* ]]; then
    for w in "${WILDCARDS[@]}"; do
      # d ends with w (".amazonaws.com") or equals its apex ("amazonaws.com")
      if [[ "${d}" == *"${w}" || ".${d}" == "${w}" ]]; then covered=1; break; fi
    done
  fi
  [[ "${covered}" -eq 0 ]] && DSTDOMAINS+=("${d}")
done

install -d -o proxy -g proxy /run/squid /var/log/squid
cat > /etc/squid/squid.conf <<EOF
# GENERATED by init-firewall.sh on container start — do not edit.
# A hostname-allowlisting forward proxy. It does NOT decrypt traffic: HTTPS is
# tunneled via CONNECT and allowed purely on the destination hostname.
http_port 3128
pid_filename /run/squid/squid.pid
cache deny all
cache_log /var/log/squid/cache.log
access_log stdio:/var/log/squid/access.log squid

acl Safe_ports port 80
acl SSL_ports port 443
acl CONNECT method CONNECT
acl allowed_domains dstdomain ${DSTDOMAINS[*]}

http_access deny !Safe_ports !SSL_ports
http_access deny CONNECT !SSL_ports
http_access allow allowed_domains
http_access deny all

# Be a quiet tunnel, not a chatty/identifiable proxy.
forwarded_for delete
via off
httpd_suppress_version_string on
EOF

squid -k parse -f /etc/squid/squid.conf   # fail loudly on a bad allowlist
squid -f /etc/squid/squid.conf             # daemonizes, drops to the proxy user

# ── 2. iptables: force everything through squid, with a base-IP fallback ─────
iptables -F OUTPUT
iptables -P OUTPUT DROP
ipset destroy egress-allow 2>/dev/null || true
ipset create egress-allow hash:ip family inet hashsize 1024 maxelem 65536

iptables -A OUTPUT -o lo -j ACCEPT                                   # → squid on 127.0.0.1:3128
iptables -A OUTPUT -p udp --dport 53 -j ACCEPT                       # DNS (squid resolves CONNECT targets)
iptables -A OUTPUT -p tcp --dport 53 -j ACCEPT
iptables -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# Direct-egress fallback: only the pinned base-infra IPs, only on 80/443. Lets a
# proxy-unaware agent runtime still reach its own API + GitHub if it ignores
# HTTPS_PROXY. Platform domains are NOT pinned — they go through squid only.
resolve_and_add() {
  for ip in $(getent ahostsv4 "$1" | awk '{print $1}' | sort -u); do
    ipset add egress-allow "${ip}" -exist
  done
}
for d in "${BASE_DOMAINS[@]}"; do resolve_and_add "${d}"; done
iptables -A OUTPUT -p tcp -m set --match-set egress-allow dst --dport 443 -j ACCEPT
iptables -A OUTPUT -p tcp -m set --match-set egress-allow dst --dport 80 -j ACCEPT

# Squid itself (the `proxy` user) may open arbitrary outbound web connections;
# it is what enforces the hostname allowlist for all proxied traffic.
iptables -A OUTPUT -m owner --uid-owner proxy -p tcp --dport 443 -j ACCEPT
iptables -A OUTPUT -m owner --uid-owner proxy -p tcp --dport 80 -j ACCEPT

iptables -A OUTPUT -j LOG --log-prefix "[research-egress-drop] " --log-level 4
iptables -A OUTPUT -j REJECT --reject-with icmp-port-unreachable

echo "[research firewall] squid allowlist: ${#DSTDOMAINS[@]} domains (${#WILDCARDS[@]} wildcard); ${#BASE_DOMAINS[@]} base domains pinned for direct fallback"
